// Generate documents
export const GENERATE_DOCUMENTS_EXP_A = 'GENERATE_DOCUMENTS_EXP_A'

///////////////////////////////


export const MOSTRAR_PRODUCTOS = 'MOSTRAR_PRODUCTOS';
export const MOSTRAR_PRODUCTO = 'MOSTRAR_PRODUCTO';
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';

/* Types Authentication */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_POSTULANT = 'LOGIN_POSTULANT';
export const LOGIN_EMPLOYER = 'LOGIN_EMPLOYER'
export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const CREATE_USER_POSTULANT = 'CREATE_USER_POSTULANT';
export const CREATE_USER_EMPLOYER = 'CREATE_USER_EMPLOYER';

/* Geographic */
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_REGIONS = 'GET_REGIONS';
export const GET_COMMUNES = 'GET_COMMUNES';
export const VALIDATE_EMAIL = 'VALIDATE_EMAIL';

/* Parameters System */
export const GET_COMMERCIAL_SECTORS = "GET_COMMERCIAL_SECTORS";
export const GET_TYPES_EMPLOYERS = "GET_TYPES_EMPLOYERS";
export const GET_NUMERICAL_RANGES = "GET_NUMERICAL_RANGES";
export const GET_POSITIONS_COMPANY = "GET_POSITIONS_COMPANY";
export const GET_EMPLOYMENT_CATEGORIES = "GET_EMPLOYMENT_CATEGORIES";
export const GET_PROFESSIONS = "GET_PROFESSIONS";
export const GET_EDUCATIONAL_LEVEL = "GET_EDUCATIONAL_LEVEL";
export const GET_IDIOMS = "GET_IDIOMS";
export const GET_TYPES_CONTRACTS = "GET_TYPES_CONTRACTS";
export const GET_TYPES_SALARIES = "GET_TYPES_SALARIES";
export const GET_TYPES_PAYMENT_PERIODICITY = "GET_TYPES_PAYMENT_PERIODICITY";

/* Change Password */
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const CHANGE_PASSWORD_USER = "CHANGE_PASSWORD_USER";

/* Employers */
export const GET_EMPLOYER = "GET_EMPLOYER";
export const UPDATE_EMPLOYER = "UPDATE_EMPLOYER";
export const SAVE_DATA_EMPLOYER = "SAVE_DATA_EMPLOYER";
export const GET_DATA_EMPLOYER = "GET_DATA_EMPLOYER";
export const GET_DATA_EMPLOYER_BY_ID = "GET_DATA_EMPLOYER_BY_ID";

export const RESET_REDUCER = "RESET_REDUCER";

/* Jobs Offers */
export const GET_JOBS_OFFERS = "GET_JOBS_OFFERS";
export const GET_JOBS_OFFERS_PUBLIC = "GET_JOBS_OFFERS_PUBLIC";
export const CREATE_JOB_OFFER = "CREATE_JOB_OFFER";
export const GET_JOBS_OFFERS_EMPLOYERS = "GET_JOBS_OFFERS_EMPLOYERS";
export const COPY_JOBS_OFFERS = "COPY_JOBS_OFFERS";
export const DISABLE_JOBS_OFFERS = "DISABLE_JOBS_OFFERS";

/* Postulant */
export const GET_POSTULANT = "GET_POSTULANT";
export const UPDATE_POSTULANT = "UPDATE_POSTULANT";
export const GET_FILTER_ADMIN = "GET_FILTER_ADMIN";
export const SET_FILTER_ADMIN = "SET_FILTER_ADMIN";

/* CV */
export const GET_CV = "GET_CV";
export const CREATE_CV = "CREATE_CV";
export const GET_CV_BY_ID = "GET_CV_BY_ID";

/* Jobs Offers Application */
export const CREATE_JOB_OFFER_APPLICATION = "CREATE_JOB_OFFER_APPLICATION";
export const EXISTS_JOB_OFFER_APPLICATION = "EXISTS_JOB_OFFER_APPLICATION";
export const GET_JOB_OFFER_APPLICATION = "GET_JOB_OFFER_APPLICATION";
export const CREATE_JOB_APPLICATION_STATE = "CREATE_JOB_APPLICATION_STATE";

export const CONTACT_CAMPAIGN = "CONTACT_CAMPAIGN";